# Site settings
title: The open forecasting project
email: koala@orion.uberspace.de
description: > # this means to ignore newlines until "baseurl:"
  New description here
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://open-fp.onnokleen.de" # the base hostname & protocol for your site
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

source: /home/onno/open-fp/open-fp
destination: /var/www/html/
exclude: [vendor]